directives:
- add_model:
    name: iiwa_controller
    file: package://drake_models/iiwa_description/sdf/iiwa14_no_collision.sdf
    default_joint_positions:
        iiwa_joint_1: [-2.70259771]
        iiwa_joint_2: [-0.70]
        iiwa_joint_3: [-0.57397568]
        iiwa_joint_4: [1.86064877]
        iiwa_joint_5: [0.65323578]
        iiwa_joint_6: [-0.68678464]
        iiwa_joint_7: [-0.52174789]
- add_weld:
    parent: world
    child: iiwa_controller::iiwa_link_0
- add_frame:
    name: iiwa_controller::ati_sensor
    X_PF:
        base_frame: iiwa_controller::iiwa_link_7
        translation: [0.0, 0.0, 0.075]
        rotation: !Rpy { deg: [-90, 0, -90]}
- add_model:
    name: peg_control
    file: file:///root/workspace/model/rectangle_peg.urdf
- add_weld:
    parent: iiwa_controller::ati_sensor
    child: peg_control::base_link
